--liquibase formatted sql

--changeset diegoluna:1

-- CREATE TABLES

CREATE TABLE team (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    teamManager NUMBER,
    teamName VARCHAR2(32) NOT NULL,
    teamDescription VARCHAR2(120) NOT NULL
)

CREATE TABLE staff (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    teamId NUMBER NOT NULL,
    firstName VARCHAR2(128) NOT NULL,
    lastName VARCHAR(128) NOT NULL,
    username VARCHAR2(32) NOT NULL,
    pass VARCHAR2(32) NOT NULL,
    phonenumber NUMBER (16) NOT NULL,
    userRole VARCHAR2(16) NOT NULL CHECK(userRole IN ('Manager', 'Developer')),
    CONSTRAINT staff_FK FOREIGN KEY (teamId) REFERENCES team(id)
);

-- CREATE INDEX FOR FAST QUERY
CREATE INDEX staff_teamId_idx ON staff(teamId);