--liquibase formatted sql

--changeset diegoluna:1

-- CREATE TABLES

CREATE TABLE task (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    assigneeId NUMBER NOT NULL,
    taskName VARCHAR2(32) NOT NULL,
    taskDescription VARCHAR2(120) NOT NULL,
    currentStatus VARCHAR2(16) NOT NULL CHECK(currentStatus IN ('ToDo', 'Ongoing', 'Done', 'Deleted')),
    creationDate TIMESTAMP NOT NULL,
    dueDate TIMESTAMP NOT NULL,
    statusChangeDate TIMESTAMP NOT NULL,
    priority NUMBER(3) NOT NULL
);

-- CREATE INDEX FOR FAST QUERIES
CREATE INDEX task_assigneeId_idx ON task(assigneeId);
CREATE INDEX task_status_idx ON task(currentStatus);
CREATE INDEX task_priority_idx ON task(priority);